---
- name: yum -y update
  yum:
    name: '*'
    state: latest
  when: "ansible_os_family == 'RedHat'"
  async: 1000
  poll: 0
  register: yum_update_async

- name: 'wait yum -y update task'
  async_status:
    jid: "{{ yum_update_async.ansible_job_id }}"
  when: "ansible_os_family == 'RedHat'"
  register: yum_update_task
  until: yum_update_task.finished
  retries: 50
  delay: 20
