all:
  hosts:
    perf-test1:
      hostname: perf-test1
      box: "rockylinux/8"
      box_version: "9.0.0"
      
      cpus: 1
      memory_size: 2048
      disk_size: 30GB

      network_interfaces:
        - type: private
          ip: 192.168.222.100
        - type: private
          ip: 192.168.223.100
      ip: 192.168.222.100

      vbguest:
        installer: 'centos'
        installer_options: { allow_kernel_upgrade: true }

      # synced_folder:
      #   - host: ../
      #     guest: /home/vagrant/podman-practice

      playbook: provisioning/setup.yml
      reboot_after_provision: true

      provision_pre_commands_bak:
        - "sudo dnf update -y"
        - "sudo dnf -y install cloud-utils-growpart"
        - "sudo dnf -y install podman podman-docker python36 git git-lfs"
        - "sudo growpart /dev/sda 4"
        - "sudo xfs_growfs /dev/sda4"
        - "sudo dnf -y install epel-release"
        - "sudo dnf -y install stress-ng iproute-tc iperf3 sysstat"
      ansible_user: vagrant

    perf-test2:
      hostname: perf-test2
      box: "rockylinux/8"
      box_version: "9.0.0"
      
      cpus: 1
      memory_size: 2048
      disk_size: 30GB

      network_interfaces:
        - type: private
          ip: 192.168.222.101
        - type: private
          ip: 192.168.223.101
      ip: 192.168.222.101

      vbguest:
        installer: 'centos'
        installer_options: { allow_kernel_upgrade: true }

      # synced_folder:
      #   - host: ../
      #     guest: /home/vagrant/podman-practice

      playbook: provisioning/setup.yml
      reboot_after_provision: true

      provision_pre_commands_bak:
        - "sudo dnf update -y"
        - "sudo dnf -y install cloud-utils-growpart"
        - "sudo dnf -y install podman podman-docker python36 git git-lfs"
        - "sudo growpart /dev/sda 4"
        - "sudo xfs_growfs /dev/sda4"
        - "sudo dnf -y install epel-release"
        - "sudo dnf -y install stress-ng iproute-tc iperf3 sysstat"
      ansible_user: vagrant


