all:
  hosts:
    alma8-podman:
      hostname: alma8-podman
      box: "almalinux/8"
      box_version: "8.9.20231219"
      
      cpus: 2
      memory_size: 8196
      disk_size: 50GB

      network_interfaces:
        - type: private
          ip: 192.168.222.11

      ip: 192.168.222.11

      vbguest:
        installer: 'centos'
        installer_options: { allow_kernel_upgrade: true }

      synced_folder:
        - host: ../
          guest: /home/vagrant/podman-practice

      provision_pre_commands:
        - "sudo dnf update -y"
        - "sudo dnf -y install cloud-utils-growpart"
        - "sudo dnf -y install podman python36 git"
        # - "sudo growpart /dev/sda 4"
        # - "sudo xfs_growfs /dev/sda4"

      ansible_user: vagrant      
